In [2]:
import pandas as pd

# Load the dataset
data = pd.read_csv('../rcv_elections_database/classic/Alaska_11082022_USRepresentative.csv')

# Display the first few rows of the dataset
data.head()

,ballotID,ballot_type,countingGroup,district,districtType,precinct,precinctPortion,votingLocation,rank1,rank2,rank3,rank4,rank5
0,91902_00000_000199,Ballot 5 - Type 5,Early Voting,Judicial District 1,Judicial,District 4 - Early Voting,District 4 - Early Voting,Region I,"Peltola, Mary S.","Bye, Chris",skipped,skipped,skipped
1,91902_00000_001588,Ballot 5 - Type 5,Early Voting,Judicial District 1,Judicial,District 4 - Early Voting,District 4 - Early Voting,Region I,"Peltola, Mary S.",skipped,skipped,skipped,skipped
2,91902_00000_002966,Ballot 4 - Type 4,Early Voting,Judicial District 1,Judicial,District 3 - Early Voting,District 3 - Early Voting,Region I,"Peltola, Mary S.","Bye, Chris","Begich, Nick",skipped,skipped
3,91902_00000_003723,Ballot 5 - Type 5,Early Voting,Judicial District 1,Judicial,District 4 - Early Voting,District 4 - Early Voting,Region I,"Peltola, Mary S.",skipped,skipped,skipped,skipped
4,91902_00000_004647,Ballot 5 - Type 5,Early Voting,Judicial District 1,Judicial,District 4 - Early Voting,District 4 - Early Voting,Region I,"Peltola, Mary S.","Begich, Nick",skipped,skipped,skipped

In [4]:
# Generate frequency distribution for each rank column
rank_columns = ["rank1", "rank2", "rank3", "rank4", "rank5"]
frequency_distributions = {}

for rank_col in rank_columns:
    frequency_distributions[rank_col] = data[rank_col].value_counts()

frequency_distributions

{'rank1': rank1
 Peltola, Mary S.    128401
 Palin, Sarah         67831
 Begich, Nick         61465
 Bye, Chris            4567
 skipped               3001
 Write-in              1107
 overvote               425
 Name: count, dtype: int64,
 'rank2': rank2
 skipped             88677
 Begich, Nick        78558
 Palin, Sarah        46680
 Bye, Chris          39720
 Peltola, Mary S.    10517
 Write-in             2451
 overvote              194
 Name: count, dtype: int64,
 'rank3': rank3
 skipped             179660
 Bye, Chris           39618
 Begich, Nick         25514
 Palin, Sarah         11440
 Peltola, Mary S.      8149
 Write-in              2274
 overvote               142
 Name: count, dtype: int64,
 'rank4': rank4
 skipped             213522
 Palin, Sarah         24195
 Bye, Chris           10789
 Peltola, Mary S.     10175
 Begich, Nick          6045
 Write-in              1950
 overvote               121
 Name: count, dtype: int64,
 'rank5': rank5
 skipped             258675
 Palin, Sarah          4311
 Peltola, Mary S.      1693
 Begich, Nick           878
 Bye, Chris             548
 Write-in               447
 overvote               245
 Name: count, dtype: int64}

In [5]:
# Combine the rank columns to form a single sequence for each ballot
data['combined_rank'] = data[rank_columns].apply(lambda x: ' -> '.join(x), axis=1)

# Count the frequency of each unique sequence
sequence_counts = data['combined_rank'].value_counts()

# Get the most common sequences (i.e., the modes)
top_sequences = sequence_counts.head(10)
top_sequences

combined_rank
Peltola, Mary S. -> skipped -> skipped -> skipped -> skipped                 52732
Begich, Nick -> Palin, Sarah -> skipped -> skipped -> skipped                26999
Palin, Sarah -> Begich, Nick -> skipped -> skipped -> skipped                26901
Palin, Sarah -> skipped -> skipped -> skipped -> skipped                     20153
Peltola, Mary S. -> Begich, Nick -> skipped -> skipped -> skipped            16048
Begich, Nick -> skipped -> skipped -> skipped -> skipped                     11258
Peltola, Mary S. -> Bye, Chris -> skipped -> skipped -> skipped              10813
Peltola, Mary S. -> Bye, Chris -> Begich, Nick -> Palin, Sarah -> skipped    10490
Peltola, Mary S. -> Begich, Nick -> Bye, Chris -> Palin, Sarah -> skipped     9194
Peltola, Mary S. -> Bye, Chris -> Begich, Nick -> skipped -> skipped          5645
Name: count, dtype: int64